defaults:
        - _self_
        - runner: eval
        - dataset: badminton
        - model: wasb
        - dataloader: default
        - detector: tracknetv2
        - transform: default
        - tracker: online
hydra:
  run:
    dir: /root/outputs/${hydra.job.name}/${now:%Y-%m-%d_%H-%M-%S}
output_dir: /content/drive/MyDrive/Object_tracking/WASB-SBDT_ball_tracking
seed: 1234

