name: soccer
root_dir: /content/drive/MyDrive/datasets/soccer
video_dirname: videos
frame_dirname: frames
anno_dirname: annos
img_ext: '.png'
video_ext: '.avi'
train:
  videos:
    - ID-1
  num_clip_ratio: 1.0
test:
  videos:
    - ID-2
  num_clip_ratio: 1.0

