name: soccer
root_dir: /mnt/datasets/soccer
video_dirname: videos
frame_dirname: frames
anno_dirname: annos
img_ext: '.png'
video_ext: '.mp4'
# train:
#   videos:
    
#   num_clip_ratio: 1.0
test:
  videos:
    - ID-1
    - ID-2
    - ID-3
    - ID-4
    - ID-5
  num_clip_ratio: 1.0

